name: Build and Deploy to AWS EBS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=prod
        working-directory: ${{ github.workspace }}

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
#    needs: build-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=prod
        working-directory: ${{ github.workspace }}

      - name: Move JAR to root directory
        run: mv target/*.jar ./
        working-directory: ${{ github.workspace }}

      - name: Create Procfile
        run: |
          echo "web: java -jar $(ls *.jar) --server.port=${{ secrets.SERVER_PORT }} --spring.config.name=application-prod" > Procfile
        working-directory: ${{ github.workspace }}

      - name: Create Procfile
        run: |
          echo "web: java -jar $(ls *.jar) --server.port=${{ secrets.SERVER_PORT }} --spring.config.name=application-prod" > Procfile
        working-directory: ${{ github.workspace }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 90

#      - name: Call Maven Workflow
#        uses: aurelien-baudet/workflow-dispatch@v2
#        with:
#          workflow: maven.yml
#          ref: ${{ github.event.pull_request.head.ref }}
#          token: ${{ secrets.WORKFLOW_TOKEN }}