name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=prod
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli
      - name: Deploy to Elastic Beanstalk
      run: |
        eb init --region us-east-1 --platform Java --keyname ${{ secrets.AWS_ACCESS_KEY_ID }} --interactive=false 
        eb deploy --staged --timeout 30
#      - name: Deploy to Elastic Beanstalk
#        uses: nohmad/elastic-beanstalk-action@master
#        with:
#          sub-command: deploy
#          environment: ${{ secrets.AWS_ENVIRONMENT_NAME }}
#          optional-args: '--nohang'
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#      - name: Deploy to Elastic Beanstalk
#        uses: einaregilsson/beanstalk-deploy@v20
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
#          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
#          version_label: ${{ github.sha }}
#          region: us-east-1
#          deployment_package: deploy.zip