name: Build and Deploy to AWS EBS

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: stock-app-workflow-group
    if: github.event.pull_request.merged == true
    steps:
    - name: Call Maven Workflow
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        workflow: maven.yml
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Check out code
      uses: actions/checkout@v2

#    - name: Move JAR to root directory
#      run: mv target/*.jar ./
#      working-directory: ${{ github.workspace }}

    - name: Create Procfile
      run: |
        echo "web: java -jar $(ls *.jar) --server.port=${{ secrets.SERVER_PORT }} --spring.config.name=application-prod" > Procfile
      working-directory: ${{ github.workspace }}

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v15
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.AWS_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
        region: ${{ secrets.AWS_REGION }}
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        wait_for_environment_recovery: 90