name: Build with Maven
on:
#  push:
#    branches: [ main, docker, docker-multi ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: stock-app-workflow-group
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: x64

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dspring.profiles.active=prod
      working-directory: ${{ github.workspace }}